name: pkg.go.dev

on:
  push:
    tags:
      - "v*"

jobs:
  pkg.go.dev:
    runs-on: ubuntu-latest
    steps:
      - curl -XGET https://proxy.golang.org/github.com/gontainer/gontainer-helpers/@v/${GITHUB_REF##*/}.info
